- name: Update and upgrade apt packages
  apt: update_cache=yes cache_valid_time=600


- name: "Installing softwares"
  apt: name={{ item }} state=installed
  with_items:
  - vim
  - python3
  - python3-pip 
