- name: "Update and upgrade apt packages"
  apt: update_cache=yes cache_valid_time=600

- name: "Install packages"
  apt: name={{ item }} state=present
  with_items:
  - vim
  - python-pip
  - git
  - curl
  

- name: "Make directories"
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
    - /doc
    - /home/ubuntu/couchdb/
    - /mnt/couchdb/


- name: "Mount volume file change"
  filesystem:
    fstype: ext4
    dev: /dev/vdb
  tags: mount

- name: "Mount volume"
  mount:
    path: /mnt/couchdb
    src: /dev/vdb
    fstype: ext4
    state: mounted
  tags: mount
