---

- name: Update and upgrade apt packages
  apt: update_cache=yes cache_valid_time=600
  tags: webserver

- name: "Install pip pkgs"
  command: 'pip install {{ item }}'
  sudo: yes
  with_items:
  - flask
  - Flask-CouchDB
  tags: webserver


- name: "Create directories"
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
  - /doc/webserver
  tags: webserver


- name: "Clone git webserver repo"
  command: git clone https://github.com/KathyXia/CCC-groupProj.git chdir={{ web_install_dir }}
  sudo: yes
  tags: webserver


- name: "Change git branch and pull"
  command: git checkout --track remotes/origin/xuanyuduan-patch-1 chdir={{ web_install_dir }}/CCC-groupProj
  sudo: yes
  tags: webserver

- name: "Copy webserver app to setup location"
  command: cp -r {{ web_install_dir }}/CCC-groupProj/web_qpp {{ web_install_dir }}
  tags: webserver

- name: "Adjust host server"
  command: sed -i 's/127.0.0.1/{{ inventory_hostname }}/g' {{ web_install_dir }}/web_qpp/app.py
  sudo: yes
  tags: webserver

- name: "Start webserver"
  shell: cd {{ web_install_dir }}/web_qpp; nohup sudo python3 app.py </dev/null >/dev/null 2>&1 &
  tags: webserver
