---
- hosts: common
  become: true
  roles:
  - basic

- hosts: dbmaster
  become: true
  roles:
  - couchdb
  - dbcluster
  vars_files:
  - ~/myplatform/roles/couchdb/vars/main.yml
  - ~/myplatform/roles/dbcluster/vars/main.yml


- hosts: dbslave
  become: true
  roles:
  - couchdb
  vars_files:
  - ~/myplatform/roles/couchdb/vars/main.yml

- hosts: analysis
  become: true
  roles:
  - analysis
  vars_files:
  - ~/myplatform/roles/analysis/vars/main.yml

- hosts: harvestapp
  become: true
  roles:
  - harvestapp
  vars_files:
  - ~/myplatform/roles/harvestapp/vars/main.yml

- hosts: webserver
  become: true
  roles:
  - webserver
  vars_files:
  - ~/myplatform/roles/webserver/vars/main.yml