---
- hosts: common
  become: true
  roles:
  - basic

- hosts: dbmaster
  become: true
  roles:
  - couchdb
  - dbcluster
  vars_files:
  - ~/myplatform/roles/couchdb/vars/main.yml
  - ~/myplatform/roles/dbcluster/vars/main.yml

