- name: Update and upgrade apt packages
  apt: update_cache=yes cache_valid_time=600
  tags: analysis

- name: "Installing softwares"
  apt: name={{ item }} state=present
  with_items:
  - python-pip
  tags: analysis

- name: "Install pip pkgs"
  command: 'pip install {{ item }}'
  sudo: yes
  with_items:
  - folium
  - nltk
  - shapely
  - pycouchdb
  - pandas
  tags: analysis


- name: "Create directories"
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
  - /doc/analysis
  tags: analysis


- name: "Clone git analysis repo"
  command: git clone https://github.com/KathyXia/CCC-groupProj.git chdir={{ als_install_dir }}
  sudo: yes
  tags: analysis


- name: "Change git branch and pull"
  command: git checkout --track remotes/origin/Minghang chdir={{ als_install_dir }}/CCC-groupProj
  sudo: yes
  tags: analysis


- name: "Unarchive data  file"
  unarchive: src={{ als_local_dir }}/data.tar.gz dest={{ als_install_dir }}
  sudo: yes
  tags: analysis

- name: "Copy analysis app to setup location"
  command: cp -r {{ als_install_dir }}/CCC-groupProj/sentiment {{ als_install_dir }}
  sudo: yes
  tags: analysis

- name: "Create directories"
  file: path={{ als_run_dir }}/{{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
  - html
  tags: analysis

- name: "Start analysis app scenarios in background"
  shell: cd {{ als_run_dir }}; nohup sudo python {{ item }} </dev/null >/dev/null 2>&1 &
  with_items:
  - scenario1.py
  - scenario2.py
  - scenario3.py
  tags: analysis