- name: "Update and upgrade apt packages"
  apt: update_cache=yes cache_valid_time=600
  tags: harvest

- name: "Installing softwares"
  apt: name={{ item }} state=present
  with_items:
  - python3
  - python3-pip
  tags: harvest

- name: "Install pip pkgs"
  command: 'pip3 install {{ item }}'
  sudo: yes
  with_items:
  - tweepy
  - numpy 
  tags: harvest


- name: "Create directories"
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
  - /doc/twitter
  - /mnt/couchdb
  - /mnt/couchdb/twitters
  tags: harvest


- name: "Install app files"
  template: src={{ item }}.j2 dest={{ twitter_app_dir }}/{{ item }}
  with_items:
  - twitter_collector.py
  - twitter_harvest.sh
  tags: harvest

- name: "start twitter harvest app in background"
  shell: cd {{ twitter_app_dir }}; nohup sudo bash twitter_harvest.sh </dev/null >/dev/null 2>&1 &
  tags: harvest

#- name: "Execute twitter harvest app"
#  command: 'sudo bash twitter_harvest.sh 2>&1 & chdir={{ twitter_app_dir }}'
#  tags: apprun


