---
- name: "Check connection to CouchDB instances"
  uri:
    url: http://{{ inventory_hostname }}:{{ item }}/
    method: GET
    status_code: 200
  with_items:
    - 5986
    - 5984
  tags: cluster

- name: "Add nodes to cluster"
  shell: curl -X PUT "http://{{ usr_name }}:{{ usr_pw }}@127.0.0.1:5986/_nodes/couchdb@{{ item }}" -d {}
  with_items: "{{ groups['dbslave'] }}"
  tags: cluster


- name: "Create databases"
  shell: curl -X PUT "http://{{ usr_name }}:{{ usr_pw }}@127.0.0.1:5984/{{ item }}"
  with_items:
    - "db_twitter_new"
    - "db_aurin_new"
    - "db_web_new"
  tags: cluster