
---
- name: "Update and upgrade apt packages"
  apt: update_cache=yes cache_valid_time=600
  tags: couchdb


- name: "Install softwares"
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - pkg-config
    - erlang
    - libmozjs185-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - nodejs
  tags: couchdb

- name: "Unarchive couchdb installation file"
  unarchive: src={{ db_local_dir }}/apache-couchdb-2.1.1.tar.gz dest={{ db_install_dir }}
  sudo: yes
  tags: couchdb

- name: "Remove erlang man"
  file: path=/usr/lib/erlang/man state=absent
  sudo: yes
  tags: couchdb


- name: "Run configure"
  shell: cd {{ db_install_dir }}/apache-couchdb-2.1.1 ; ./configure && make release
  sudo: yes
  tags: couchdb


- name: "Change config files"
  template: src={{ item }}.j2 dest={{ db_exe_dir }}/etc/{{ item }}
  with_items:
  - local.ini
  - vm.args
  - default.ini
  tags: couchdb

- name: "Change config files"
  template: src={{ item }}.j2 dest={{ db_exe_dir }}/releases/2.1.1/{{ item }}
  with_items:
  - sys.config
  tags: couchdb

- name: "Run couchdb"
  shell: cd {{ db_exe_dir }}/bin; sudo nohup ./couchdb </dev/null> log.out 2>&1 &
  tags: couchdb




